package start;

import config.GameAssets;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class Start extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Start.class.getName());

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jhumanBtn = new javax.swing.JButton();
        jComputerBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuAuthor = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batership");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Hello Everyone!!! ");

        jhumanBtn.setBackground(new java.awt.Color(255, 102, 102));
        jhumanBtn.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 24)); // NOI18N
        jhumanBtn.setText("Play with human");
        jhumanBtn.addActionListener(this::jhumanBtnActionPerformed);

        jComputerBtn.setBackground(new java.awt.Color(0, 153, 153));
        jComputerBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jComputerBtn.setText("Play with computer");
        jComputerBtn.addActionListener(this::jComputerBtnActionPerformed);

        jMenuExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuExit.setText("Exit  ");
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuExitMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        jMenuAuthor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuAuthor.setText("Author");
        jMenuAuthor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuAuthorMousePressed(evt);
            }
        });
        jMenuBar1.add(jMenuAuthor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jhumanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComputerBtn)
                    .addComponent(jLabel1))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jComputerBtn)
                .addGap(26, 26, 26)
                .addComponent(jhumanBtn)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAuthorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAuthorMousePressed
       JOptionPane.showMessageDialog(this, "Author: Sadowski Paweł", "Author", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuAuthorMousePressed

    private void jMenuExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_jMenuExitMousePressed

    private void jComputerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComputerBtnActionPerformed
        new Game(GameAssets.mode.VS_COMPUTER);
        dispose();
    }//GEN-LAST:event_jComputerBtnActionPerformed

    private void jhumanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhumanBtnActionPerformed
        new Game(GameAssets.mode.VS_HUMAN);
        dispose();
    }//GEN-LAST:event_jhumanBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Start().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jComputerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAuthor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JButton jhumanBtn;
    // End of variables declaration//GEN-END:variables
}
